name: Build Docker and Optional Push

on:
  push:
    branches:
      - main
      - dev
      - demo
      - hotfix
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - dev
      - demo
      - hotfix
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        if: ${{ (github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo' || github.ref_name == 'hotfix') }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set Docker image tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/demo" ]]; then
            echo "TAG=demo" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/hotfix" ]]; then
            echo "TAG=hotfix" >> $GITHUB_ENV
          else
            echo "TAG=pullrequest-ignore" >> $GITHUB_ENV
          fi

      - name: Build and push contentprocessor Docker image
        run: |
          cd src/ContentProcessor
          # Use lowercase image name to meet Docker naming requirements
          if [[ "${{ env.TAG }}" == "pullrequest-ignore" ]]; then
            IMAGE_NAME="contentprocessor:${{ env.TAG }}"
          else
            IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/contentprocessor:${{ env.TAG }}"
          fi
          echo "Using image name: ${IMAGE_NAME}"
          docker build -t ${IMAGE_NAME} -f Dockerfile .
          if [[ "${{ env.TAG }}" == "latest" || "${{ env.TAG }}" == "dev" || "${{ env.TAG }}" == "demo" || "${{ env.TAG }}" == "hotfix" ]]; then
            docker push ${IMAGE_NAME}
            echo "contentprocessor image built and pushed successfully."
          else
            echo "Skipping Docker push for contentprocessor with tag: ${{ env.TAG }}"
          fi

      - name: Build and push contentprocessorapi Docker image
        run: |
          cd src/ContentProcessorAPI
          if [[ "${{ env.TAG }}" == "pullrequest-ignore" ]]; then
            IMAGE_NAME="contentprocessorapi:${{ env.TAG }}"
          else
            IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/contentprocessorapi:${{ env.TAG }}"
          fi
          echo "Using image name: ${IMAGE_NAME}"
          docker build -t ${IMAGE_NAME} -f Dockerfile .
          if [[ "${{ env.TAG }}" == "latest" || "${{ env.TAG }}" == "dev" || "${{ env.TAG }}" == "demo" || "${{ env.TAG }}" == "hotfix" ]]; then
            docker push ${IMAGE_NAME}
            echo "contentprocessorapi image built and pushed successfully."
          else
            echo "Skipping Docker push for contentprocessorapi with tag: ${{ env.TAG }}"
          fi

      - name: Build and push contentprocessorweb Docker image
        run: |
          cd src/ContentProcessorWeb
          if [[ "${{ env.TAG }}" == "pullrequest-ignore" ]]; then
            IMAGE_NAME="contentprocessorweb:${{ env.TAG }}"
          else
            IMAGE_NAME="${{ secrets.ACR_LOGIN_SERVER }}/contentprocessorweb:${{ env.TAG }}"
          fi
          echo "Using image name: ${IMAGE_NAME}"
          docker build -t ${IMAGE_NAME} -f Dockerfile .
          if [[ "${{ env.TAG }}" == "latest" || "${{ env.TAG }}" == "dev" || "${{ env.TAG }}" == "demo" || "${{ env.TAG }}" == "hotfix" ]]; then
            docker push ${IMAGE_NAME}
            echo "contentprocessorweb image built and pushed successfully."
          else
            echo "Skipping Docker push for contentprocessorweb with tag: ${{ env.TAG }}"
          fi
