name: Test Workflow

on:
  push:
    branches:
      - main
      - dev
      - demo
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'src/**/requirements.txt'
      - 'src/**/pyproject.toml'
      - 'src/**/pytest.ini'
      - 'src/**/conftest.py'
      - '.github/workflows/test.yml'
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - dev
      - demo
      - dependabotchanges
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'src/**/requirements.txt'
      - 'src/**/pyproject.toml'
      - 'src/**/pytest.ini'
      - 'src/**/conftest.py'
      - '.github/workflows/test.yml'
permissions:
  contents: read
  actions: read
  pull-requests: write
jobs:
  backend_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/ContentProcessor/requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Check if Backend Test Files Exist
        id: check_backend_tests
        run: |
          if [ -z "$(find src/ContentProcessor/src/tests -type f -name 'test_*.py')" ]; then
            echo "No backend test files found, skipping backend tests."
            echo "skip_backend_tests=true" >> $GITHUB_ENV
          else
            echo "Backend test files found, running tests."
            echo "skip_backend_tests=false" >> $GITHUB_ENV
          fi

      - name: Run Backend Tests with Coverage
        if: env.skip_backend_tests == 'false'
        run: |
          cd src/ContentProcessor
          python -m pytest -vv --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=80 --junitxml=pytest.xml

      - name: Pytest Coverage Comment
        if: |
          always() &&
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.fork == false &&
          env.skip_backend_tests == 'false'
        uses: MishaKav/pytest-coverage-comment@26f986d2599c288bb62f623d29c2da98609e9cd4  # v1.6.0
        with:
          pytest-xml-coverage-path: src/ContentProcessor/coverage.xml
          junitxml-path: src/ContentProcessor/pytest.xml
          report-only-changed-files: true

      - name: Skip Backend Tests
        if: env.skip_backend_tests == 'true'
        run: echo "Skipping backend tests because no test files were found."

  # frontend_tests:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "20"
